name: "Incremental coverage check"
description: "Incremental coverage check"
author: "Velis"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: wip
    - run: echo Hello.
      shell: bash
    - run: ls -lah
      shell: bash
    - run: pwd
      shell: bash
