name: "Incremental coverage check"
description: "Incremental coverage check"
author: "Velis"
inputs:
  coverage_json:
    description: "Coverage json"
    default: ""
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: wip
        path: icc
    - run: echo Hello.
      shell: bash
    - run: ls -lah
      shell: bash
    - run: pwd
      shell: bash
    - run: ls -lah icc
      shell: bash
    - run: pip3 install -r icc/requirements.txt
      shell: bash
    - run: python3 icc/main.py -b $GITHUB_BASE_REF!
      shell: bash

