name: "Incremental coverage check"
description: "Incremental coverage check"
author: "Velis"
inputs:
  coverage_json:
    description: "Coverage json"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: wip
        path: icc
    - run: pip3 install -r icc/requirements.txt
      shell: bash
    - run: python3 icc/main.py -w ${{ github.workspace }} -c ${{ github.head_ref }}  -b ${{ github.base_ref }} -j ${{ github.workspace }}/${{ inputs.coverage_json }}
      shell: bash

